In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [4]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1] #맨뒤에 있는 행이 -1
  print("X=",input_features)
  
  labels = np.reshape(data[:,-1],(4,1)) #행 형태로 바꿈 - 1행 4열로 바꿈
  print("Y=",labels)
 
  input_features = torch.tensor(input_features, dtype=torch.float)
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/My Drive/colab/ann/xor1/train.txt")

# layer 1 가중치 초기화
# 이곳을 완성하세요.
w1 = torch.randn(2, 2, requires_grad=True) #2x2 matrix, random 정규분포, grandient를 이용해서 update
b1 = torch.randn(2, requires_grad=True)

print("\n[Init]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))

# layer 2 가중치 초기화
# 이곳을 완성하세요.
w2 = torch.randn(2, 1, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)

print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# Activation 함수 설정
sigmoid = nn.Sigmoid() #1.0/(1.0 + e ...) -> 값이 너무 작아져서 underflow가 발생

# 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss() #Binary Cross Entropy

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1,b1,w2,b2],lr=0.2) #SGD는 torch에 구현됨.- Stochastic Gradient Descent, learning rate를 0.2로 줌

# 모델 학습
for epoch in range(1001):

    # H(X) 계산: forward 연산
    # 이곳을 완성하세요.
    L2 = sigmoid(torch.add(torch.matmul(x, w1), b1)) #x * w1 + b1을 sigmoid에 집어넣음
    hx = sigmoid(torch.add(torch.matmul(L2, w2), b2)) # WL + b 에서 sigmoid -> y^-

 #backpropagation - gradient update
    # 비용 계산
    cost = loss_func(hx, y)
    # 역전파 수행
    cost.backward()
    optimizer.step()

    # 100 에폭마다 비용 출력 - cost가 0에 가까워지면 break
    if epoch % 100 == 0:
        print(epoch, cost.item()) 

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# 모델 평가
# H(X) 계산: forward 연산
# 이곳을 완성사에요.
L2 = sigmoid(torch.add(torch.matmul(x, w1), b1))
hx = sigmoid(torch.add(torch.matmul(L2, w2), b2))

logits = (hx > 0.5).float()
predicts = tensor2list(logits)
golds = tensor2list(y)

print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))

DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[-0.11948607861995697, -0.5161756873130798], [1.2274647951126099, 0.7439289689064026]]
b1 = [1.011786937713623, 2.042276620864868]
w2 = [[-0.7945892810821533], [1.3063344955444336]]
b2 = [1.034568428993225]

0 0.9715384244918823
100 0.6784604787826538
200 0.5699792504310608
300 0.501580536365509
400 0.47861599922180176
500 0.5286930799484253
600 0.597124457359314
700 0.60075443983078
800 0.5352240800857544
900 0.4801490902900696
1000 0.4971943199634552

[Learned]
w1 = [[-151.41317749023438, -43.772186279296875], [176.28810119628906, -59.59593963623047]]
b1 = [75.93206787109375, -105.58467102050781]
w2 = [[-143.8271026611328], [-73.28816223144531]]
b2 = [142.9437255859375]


PRED= [[0.0], [0.0], [1.0], [0.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 0.750000
