In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [74]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1]
  print("X=",input_features)
  
  labels = np.reshape(data[:,-1],(4,1))
  print("Y=",labels)
 
  input_features = torch.tensor(input_features, dtype=torch.float)
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/My Drive/colab/ann/xor1/train.txt")

# layer 1 가중치 초기화
# 이곳을 완성하세요.

print("\n[Init]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))

# layer 2 가중치 초기화
# 이곳을 완성하세요.

print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# Activation 함수 설정
sigmoid = nn.Sigmoid()

# 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss()

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1,b1,w2,b2],lr=0.2)

# 모델 학습
for epoch in range(1001):

    # H(X) 계산: forward 연산
    # 이곳을 완성하세요.

    # 비용 계산
    cost = loss_func(hx, y)
    # 역전파 수행
    cost.backward()
    optimizer.step()

    # 100 에폭마다 비용 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# 모델 평가
# H(X) 계산: forward 연산
# 이곳을 완성사에요.

logits = (hx > 0.5).float()
predicts = tensor2list(logits)
golds = tensor2list(y)

print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))

DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[-0.668328046798706, 0.5918465256690979], [-0.36511167883872986, -0.6000574827194214]]
b1 = [-0.9711222052574158, 0.19410347938537598]
w2 = [[1.1010056734085083], [-0.5973880290985107]]
b2 = [0.16725173592567444]

0 0.6972437500953674
100 0.5807050466537476
200 0.0013448626268655062
300 0.00010562681563897058
400 1.2934542610310018e-05
500 1.4603181170969037e-06
600 1.7881399116959074e-07
700 2.9802322387695312e-08

[Learned]
w1 = [[-112.27774047851562, 102.93649291992188], [61.72703552246094, -104.60399627685547]]
b1 = [101.88740539550781, 58.08322525024414]
w2 = [[-139.24635314941406], [-70.98396301269531]]
b2 = [155.9149169921875]


PRED= [[0.0], [1.0], [1.0], [0.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 1.000000
